//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class faktury
    {
        [Required]
        public int id { get; set; }

        [Required]
        public int nr_umowy { get; set; }

        [Required]
        public string rodzaj_platnosci { get; set; }

        [Required]
        public System.DateTime termin_platnosci { get; set; }

        [Required]
        public System.DateTime data_wystawienia { get; set; }

        [Required(ErrorMessage = "Pole wartoœæ jest wymagane")]
        [Range(1, Double.MaxValue, ErrorMessage = "Wartoœæ powinna byæ wiêksza ni¿ 1")]
        public double wartosc { get; set; }
    
        public virtual umowy umowy { get; set; }
    }
}
