//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faktury
    {
        public int id { get; set; }
        public int nr_zlecenia { get; set; }
        public string typ { get; set; }
        public string rodzaj_platnosci { get; set; }
        public System.DateTime termin_platnosci { get; set; }
        public System.DateTime data_wystawienia { get; set; }
    
        public virtual zlecenia zlecenia { get; set; }
    }
}
