//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kierownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kierownicy()
        {
            this.grupy_robocze = new HashSet<grupy_robocze>();
            this.zlecenia = new HashSet<zlecenia>();
        }

        [Required]
        public int id { get; set; }

        [Required]
        [Range(999, 99999, ErrorMessage = "Podaj wartoœæ z zakresu <999, 9999>")]
        public double wynagrodzenie { get; set; }
    
        public virtual dane_personalne dane_personalne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupy_robocze> grupy_robocze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zlecenia> zlecenia { get; set; }
    }
}
