//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klienci()
        {
            this.zgloszenia = new HashSet<zgloszenia>();
        }

        [Required]
        public int id { get; set; }

        [StringLength(50, ErrorMessage = "Nazwa może mieć maksymalnie 50 znak�w")]
        public string nazwa_firmy { get; set; }

        [RegularExpression("^[0-9]{10}$", ErrorMessage = "NIP musi mieć 10 cyfr")]
        public string nip { get; set; }

        public virtual dane_personalne dane_personalne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zgloszenia> zgloszenia { get; set; }
    }
}