//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class magazyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public magazyny()
        {
            this.materialy = new HashSet<materialy>();
        }

        [Required]
        public int id { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Nazwa mo¿e mieæ maksymalnie 30 znaków")]
        public string nazwa { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Adres mo¿e mieæ maksymalnie 50 znaków")]
        public string adres { get; set; }

        [Required(ErrorMessage = "Pole stan wype³nienia jest wymagane")]
        [Range(0, 100, ErrorMessage = "Stan wype³nienia to liczba z zakresu <0, 100>")]
        public int stan_wypelnienia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialy> materialy { get; set; }
    }
}
