//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class maszyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maszyny()
        {
            this.pracownicy = new HashSet<pracownicy>();
        }

        [Required]
        public int id { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Nazwa mo¿e mieæ maksymalnie 30 znaków")]
        public string nazwa { get; set; }

        [Required]
        public bool sprawna { get; set; }

        [Required]
        public bool zajeta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pracownicy> pracownicy { get; set; }
    }
}
