//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class materialy
    {
        [Required]
        public int id { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Nazwa może mieć maksymalnie 30 znaków")]
        public string nazwa { get; set; }

        [Required(ErrorMessage = "Pole ilość jest wymagane")]
        [Range(0.0001, Double.MaxValue, ErrorMessage = "Ilość musi być większa od zera")]
        public double ilosc { get; set; }

        [Required(ErrorMessage = "Pole wartość jest wymagane")]
        [Range(0.0001, Double.MaxValue, ErrorMessage = "Wartość musi być większa od zera")]
        public double wartosc { get; set; }

        [Required]
        public int zarezerwowany_dla { get; set; }


        public Nullable<int> dostepny_w { get; set; }

        public virtual magazyny magazyny { get; set; }
        public virtual zlecenia zlecenia { get; set; }
    }
}
