//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dane_personalne> dane_personalne { get; set; }
        public virtual DbSet<faktury> faktury { get; set; }
        public virtual DbSet<grupy_robocze> grupy_robocze { get; set; }
        public virtual DbSet<kierownicy> kierownicy { get; set; }
        public virtual DbSet<klienci> klienci { get; set; }
        public virtual DbSet<magazyny> magazyny { get; set; }
        public virtual DbSet<maszyny> maszyny { get; set; }
        public virtual DbSet<materialy> materialy { get; set; }
        public virtual DbSet<pracownicy> pracownicy { get; set; }
        public virtual DbSet<umowy> umowy { get; set; }
        public virtual DbSet<zgloszenia> zgloszenia { get; set; }
        public virtual DbSet<zlecenia> zlecenia { get; set; }
    }
}
