//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pracownicy
    {
        [Required]
        public int id { get; set; }

        [Required]
        public int grupa_robocza { get; set; }
        public Nullable<int> obslugiwana_maszyna { get; set; }

        [Required]
        [Range(999, 99999, ErrorMessage = "Podaj wartoœæ z zakresu <999, 9999>")]
        public double wynagrodzenie { get; set; }

        public virtual dane_personalne dane_personalne { get; set; }
        public virtual grupy_robocze grupy_robocze { get; set; }
        public virtual maszyny maszyny { get; set; }
    }
}