//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma_budowlana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class zlecenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zlecenia()
        {
            this.materialy = new HashSet<materialy>();
            this.umowy = new HashSet<umowy>();
        }

        [Required]
        public int id { get; set; }

        [Required]
        public int nr_zgloszenia { get; set; }

        [Required]
        public int kierownik { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Etap może mieć maksymalnie 250 znak�w")]
        public string etap { get; set; }

        [Required]
        [Range(0, 100, ErrorMessage = "Postęp musi być w zakresie <0, 100>")]
        public int postep { get; set; }

        [Required(ErrorMessage = "Pole szacunkowy koszt jest wymagane")]
        public double szacunkowy_koszt { get; set; }

        [Required]
        public System.DateTime termin { get; set; }

        public virtual kierownicy kierownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialy> materialy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umowy> umowy { get; set; }
        public virtual zgloszenia zgloszenia { get; set; }
    }
}